### ISSUE TITLE
[PE-D][Tester B] Do you think that price should be $0? idk.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-1/tp#211]
![image.png](https://raw.githubusercontent.com/UnwilledTangent/ped/main/files/16b9425c-80e0-4891-b1b9-ee3bcf062bfe.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: UnwilledTangent/ped#3

**Comment by Johnchiahk** [comment]
Yes.
