### ISSUE TITLE
[PE-D][Tester D] find-project command format in application does not match UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T14-1/tp#225]
![Screenshot 2023-03-31 145110.png](https://raw.githubusercontent.com/redHat-arko/ped/main/files/606fa3d0-e481-4ad4-94eb-a0bfb14878fb.png)

delete-project command format in application does not match UG

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: redHat-arko/ped#14

**Comment by zrei** [comment]
Fixed by #244
