### ISSUE TITLE
[PE-D][Tester D] find-project does not work as intended with special characters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T14-1/tp#228]
![Screenshot 2023-03-31 145755.png](https://raw.githubusercontent.com/redHat-arko/ped/main/files/dcdc6373-68ec-4f01-8dd7-26c50b1cf30b.png)

find-project should return nothing found if there are no matches but instead it returns at least one valid parameter should be provided.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: redHat-arko/ped#15

**Comment by zrei** [comment]
Fixed by UG update
