### ISSUE TITLE
[PE-D][Tester B] Not enough visuals for command?

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T14-1/tp#238]
The only screenshot I see in the User Guide is at the Quick Start. I thought it would be better if you provided screenshots for all commands, so that the reader have a easier time reading and visualizing and understanding the commands

I would like to quote from the textbook:

These are considered UG bugs (if they hinder the reader):

 Use of visuals

Not enough visuals e.g., screenshots/diagrams

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: UnwilledTangent/ped#7

**Comment by zrei** [comment]
Closed by UG updates
